# Generated by Django 4.0.3 on 2022-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_job_isreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='jobSkills',
            field=models.ManyToManyField(blank=True, to='app1.skill'),
        ),
    ]
