# Generated by Django 3.2.8 on 2022-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='isDeclined',
            field=models.BooleanField(default=False),
        ),
    ]
