# Generated by Django 3.2.8 on 2022-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_userprofile_preferrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferRating',
            field=models.CharField(blank=True, choices=[('Ratings', 'Ratings'), ('Proximity', 'Proximity')], max_length=50, null=True),
        ),
    ]
