# Generated by Django 3.2.8 on 2022-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220315_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='jobType',
        ),
    ]
