# Generated by Django 3.2.8 on 2022-03-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_jobpost_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
